import os
ini_file = """# This file contains the MinecraftEdu Client settings. Some of these settings can be configured using the MinecraftEdu Settings menu in the Client Settings Menu.

# Set to true to hide the 'back to start menu' button from main menu. Default: false
disable-startmenu=false

# Set a path to to the custom folder for your singleplayer saves. Default: blank
customsavefolder=

custom-screenshots-folder=

# Set to true to show the 'statistics' button in the settings menu. Default: false
showstats=false

# Set to true to use advanced build mode. Default: false
advancedbuildmode=false

# Set to true to show achievements and the achievements button in the settings menu. Default: false
showachievements=false

# Set to false to hide tooltips for some settings to explain what they are. Default: true
tooltips=true

# Set to false to disable the visual aid for building modes. Default: true
visualfill=true

# Set to true to remove the singleplayer button from main menu. Default: false
disable-sp=true

# Set to false to prevent downloading and utilize texture packs if MinecraftEdu Server has one set in it's world. Default: true
allow-server-texturepacks=true

# Language for MinecraftEdu functionality in the client. Generated by MinecraftEdu Applications, should not be changed by hand. Default: en
lang=en

# Set to true to use your own custom Mojang skin in game. Requires you to use login mode 'Mojang Account' and login. Default: false
use-custom-skin=false

"""
Computers = ["Lexichild002","Lexichild003", "LexiChild004", "Lexichild006", "Lexichild007", "Lexichild011"]

for computer in Computers:
    path = "\\\\" + computer + "\\C$\\minecraftedu\\minecraft\\"
    file_path = path + "minecraftedusettings.ini"
    print(file_path)
    if(os.path.isfile(file_path)):
        os.remove(file_path)
        print(file_path + "  removed\n")
        target = open(file_path, 'w')
        print("wrote to :  " + file_path)
        target.write(ini_file)
        target.close()
        print("closing")
    
        
    
